services:
  web:
    build:
      context: match_service
      target: builder
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - MONGO_URL=${MONGO_URL}
    restart: always
    ports: 
      - '8001:8000'
