# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

env:
  SECRET_KEY: 'django-insecure-8*23gd&8$quu(fy6j4$1h24##xv6#@%%d&fd+$0&63e)m4$(!@'
  DEBUG: 1
  MONGO_URL: 'mongodb+srv://calat:1234@cluster0.i1yihyt.mongodb.net/?retryWrites=true&w=majority' # Se debe cambiar con la DB respectiva

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 Django pytest-django
        if [ -f match_service/requirements.txt ]; then pip install -r match_service/requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        cd match_service
        pytest
